### ISSUE TITLE
client page development

### ISSUE THREAD

**Issue by rrgks6221** [rrgks6221/barogo-dev-task#21]
### Summary

client page development

### description

- 자판기와 유사한 화면을 위한 client side 개발
- 추가로 필요한 api 생성
- 버그가 있는 api 수정

### To-Do

- [x] client side 개발
- [x] 추가로 필요한 api 생성
- [x] 버그가 있는 api 수정

### API

| Method | Path      | 설명           | 작업(추가, 수정, 삭제) |
| ------ | --------- | -------------- | ---------------------- |
|GET|api/payment-status|결제상태 조회|추가|
|GET|api/amount|잔여금액 조회|추가|
