### ISSUE TITLE
문서 고도화 및 버그 수정

### ISSUE THREAD

**Issue by rrgks6221** [rrgks6221/barogo-dev-task#23]
### Summary

문서 고도화

### description

문서 고도화

### To-Do

- [x] MECHANISM.png 수정
- [x] REQUIREMENTS_DEFINiTION.md
- [x] README.md
- [x] 각 api router 에 간단한 api 설명 주석
- [x] package.json

### API

| Method | Path      | 설명           | 작업(추가, 수정, 삭제) |
| ------ | --------- | -------------- | ---------------------- |
