### ISSUE TITLE
api base code create cli

### ISSUE THREAD

**Issue by rrgks6221** [rrgks6221/barogo-dev-task#7]
### Summary

api 베이스코드 생성 cli

### description

api 베이스코드 생성 cli script 생성

### To-Do

- [x] api 베이스코드 생성 cli script 생성
  - [x] controller / controller.spec
  - [x] service / service.spec

### API

| Method | Path      | 설명           | 작업(추가, 수정, 삭제) |
| ------ | --------- | -------------- | ---------------------- |
